### ISSUE TITLE
Docker image version number environment variable

### ISSUE THREAD

**Issue by curtisma** [iic-jku/iic-osic-tools#10]
## **Is your feature request related to a problem? Please describe.**
It can be hard to tell which version of the container is used.  Especially if you are just using it as a base image in another docker file or devcontainer.

## **Describe the solution you'd like**

There should be an environment variable, `IIC_OSIC_TOOLS_VERSION`, defining the image version used for that container.  This will allow users to easily see what image version was used from within the running container.

From [this issue](https://github.com/iic-jku/iic-osic/issues/3#issuecomment-1519058053):
> > Is there a way to check the version number from within it?
> 
> Unfortunately not, but I guess this would be a good idea going forward. I am thinking of an env var like `IIC-OSIC-TOOLS` giving the Docker like `2023.04`.

## **Describe alternatives you've considered**

None yet

## **Additional context**

I couldn't tell what version I was using for the bug report in issue https://github.com/iic-jku/iic-osic-tools/issues/9

**Comment by hpretl** [comment]
This will be implemented as part part of the next release, see https://github.com/iic-jku/iic-osic-tools/commit/2ed53a98a0d524de567c2f61862de49500097ed9.
