### ISSUE TITLE
Support for Chisel

### ISSUE THREAD

**Issue by schoeberl** [iic-jku/IIC-OSIC-TOOLS#12]
**Is your feature request related to a problem? Please describe.**
This feature request is not related to a real problem but a nice to have.

To support Chisel for design entry we need a JVM, e.g., OpenJDK and sbt.
The rest (Scala, Chisel) will be downloaded automatically on the first run of sbt.

**Comment by hpretl** [comment]
I'll put it onto our TODO list. I guess we should also include FIRRTL, or is Chisel enough by itself?
