### ISSUE TITLE
VNC mode does not need docker unconfined security setting?

### ISSUE THREAD

**Issue by DanielGerlicher** [iic-jku/IIC-OSIC-TOOLS#22]
Is this setting really required?

The container still works for me after removing this option.

https://github.com/iic-jku/IIC-OSIC-TOOLS/blob/c7ee2e43ade70c55375888ce3db98a5c928a52bd/start_vnc.sh#L98C43-L98C43

**Comment by hpretl** [comment]
@MrHighVoltage Can you please check this? If really not needed, let's get rid of it.

**Comment by MrHighVoltage** [comment]
Okay, so it seems that it is not even needed for the locally running X-server, at least I tried it on a few machines (with and without SELinux, local X, XRDP etc.).

Thanks for bringing that up, the start scripts have been updated!

**Comment by DanielGerlicher** [comment]
vscode seems to need it
