### ISSUE TITLE
alias xschem as "xschem -b" prevent the other alias xschemtcl to enter tcl cmd mode

### ISSUE THREAD

**Issue by cnMuggle** [iic-jku/IIC-OSIC-TOOLS#27]
**Describe the bug**
the original xschem cmd from stefan when used, will return a TCL cmd. The default setting in iic-osic is to alias xschem as "xschem -b" in ~/.bashrc file. This setting results in the other alias "xschemtcl", which is supposed to behave like original, output TCL cmd, doesn't work and behave the same as "xschem -b". 

**To Reproduce**
1. I use icc-osic-tool-xserver in windows OS
2. after start it, the cmd shows up, type "xschemtcl"
3. the return doesn't have TCL cmd and hence I must have & to send it to the background.
![image](https://github.com/iic-jku/IIC-OSIC-TOOLS/assets/10713939/19abd5ce-4fe2-4d14-8842-b613bf6c42d7)

**Expected behavior**
The below results are obtained via the tricks in the Additional context.
![image](https://github.com/iic-jku/IIC-OSIC-TOOLS/assets/10713939/4874b33c-827f-428a-823e-13afe70065c3)

**Screenshots**

**Environment:**
 - OS: Windows
 - Operating mode: both mode, X11 and xvnc (http://localhost)
 - Version tag : **where to find this info? I download from github last month on Dec/2023**

**Additional context**
One workaround is to define "xschem -b" as something else, like **xschem_b**, but not replace the app name "xschem". What I show below in .bashrc is a possible work around. The line of "unalias xschem" is needed for de-link the existing xschem from 'xschem -b'
![image](https://github.com/iic-jku/IIC-OSIC-TOOLS/assets/10713939/af6596c7-ff82-4667-a94e-fb9e2b87740c)

It looks like even xschemtcl will call the "xschem -b" if alias xschem is renmaed as 'xschem -b' no matter I put the xschemtcl alias definition before or after the 'xschem -b' alias. I have tried to code in the below two ways but xschemtcl still doesn't function properly.
![image](https://github.com/iic-jku/IIC-OSIC-TOOLS/assets/10713939/01d86259-b5e3-46b8-876f-04d088921851)
or
![image](https://github.com/iic-jku/IIC-OSIC-TOOLS/assets/10713939/8067136c-eeef-4e95-aba6-a111d949dd57)

I don't plan to file a Pull request because I think it's kind of personal preference to overwrite 'xschem' as 'xschem -b' and not using xschem_b or something like that. It's just unfortunately that somehow the defined "xschemtcl" doesn't work anymore. A more fundamental solution should fix this issue somewhere else, maybe in xschem or BASH. It sounds to me maybe this work previously but not now.

**Comment by hpretl** [comment]
Thank you, you raised an important point. The solution is rather simple, as using `\` an alias is not used. So we will update this accordingly in the next release:

`alias xschemtcl='\xschem --rcfile $PDKPATH/libs.tech/xschem/xschemrc'`

**Comment by hpretl** [comment]
Fixed: https://github.com/iic-jku/IIC-OSIC-TOOLS/commit/726e50996e26d552ea49209da09603568848eb1f
