### ISSUE TITLE
Feature request: ipympl

### ISSUE THREAD

**Issue by bmurmann** [iic-jku/IIC-OSIC-TOOLS#34]
Would be nice to have https://github.com/matplotlib/ipympl installed by default. This enables nice interactive plots in Jupyter notebooks (%matplotlib widget).

**Comment by hpretl** [comment]
Package added, will be part of next release. See https://github.com/iic-jku/IIC-OSIC-TOOLS/commit/b7cab47fcf4291984cda62193d9a2376a3f98341
