### ISSUE TITLE
HTTP/s proxy regression

### ISSUE THREAD

**Issue by martinjankoehler** [iic-jku/IIC-OSIC-TOOLS#35]
**Describe the bug**

In branch `next_release`, since f0da7598e76abd36e84ea1bd8d5243c14bfc1ab4 `gpg` is used to retrieve the keyring.
However, behind a proxy (see PR #26), the `gpg` invocation will run into a timeout, as `gpg` does not handle proxy settings by default.

![image](https://github.com/iic-jku/IIC-OSIC-TOOLS/assets/29398377/5576dcd8-b64d-4885-843f-11d0e0f51558)

The solution is, in case of a proxy, to add `--keyserver-options http-proxy=$http_proxy`.
![image](https://github.com/iic-jku/IIC-OSIC-TOOLS/assets/29398377/f934dd71-5f85-4a98-908d-126cf9093ce0)

**Comment by MrHighVoltage** [comment]
Closed with accepting PR #36
