### ISSUE TITLE
uninstall procedure 

### ISSUE THREAD

**Issue by ripudamank2** [iic-jku/IIC-OSIC-TOOLS#50]
whats the procedure to uninstall iic-osic-tool   from ubuntu machine . 
I  am running out of memory

**Comment by hpretl** [comment]
1. You can list running container with `docker container ls`. This shows all the `CONTAINERID`.
2. Stop all of them using `docker container stop <CONTAINERID>`. 
3. Then show all the images with `docker image ls`. 
4. Remove all images with `docker image rm <IMAGEID>`.
5. Remove the directory where you have cloned the GitHub repo.
