### ISSUE TITLE
Extend and prepare image for PULP platform

### ISSUE THREAD

**Issue by hpretl** [iic-jku/IIC-OSIC-TOOLS#54]
To support SoC builds of the PULP platform from ETH Zurich, the following additional SW packages are needed:

Bender: https://github.com/pulp-platform/bender
Morty: https://github.com/pulp-platform/morty
SVase: https://github.com/pulp-platform/svase
Verible: https://github.com/chipsalliance/verible
SV2V: https://github.com/zachjs/sv2v

**Comment by hpretl** [comment]
First implementation finished with commit dd0421fe0caa4aa078ddaeed94cfd7f92b1b0005. Will thus be part of next release.

**Comment by phsauter** [comment]
I just tested the tools and they all work as expected.

**Comment by hpretl** [comment]
Excellent, thanks!
