### ISSUE TITLE
Can we have xcircuit in future release?

### ISSUE THREAD

**Issue by svenn71** [iic-jku/IIC-OSIC-TOOLS#57]
I would like to ask for xcircuit in a future release.
xcircuit is a very convenient and mature drawing application with support for spice netlist generation.

http://opencircuitdesign.com/xcircuit/

**Comment by hpretl** [comment]
Good idea, could be useful for circuit drawing. Added with 112734795f8a781aa42923d507f8ce52255fe3d7, will be part of next release.

**Comment by hpretl** [comment]
Build works for `x86_64`, but fails on `aarch64`. An issue with XCircuit is opened https://github.com/RTimothyEdwards/XCircuit/issues/21

Now have to wait for resolution.

**Comment by hpretl** [comment]
Build issues are fixed, will be part of next release.
