### ISSUE TITLE
Verilator requires perl-doc

### ISSUE THREAD

**Issue by phsauter** [iic-jku/IIC-OSIC-TOOLS#58]
**Describe the bug**
Verilator requires the `perl-doc` package for its help message.
Without this `verilator --help` simply outputs:
```
You need to install the perl-doc package to use this program.
```

**To Reproduce**
In the container:
```
verilator --help
```

**Comment by hpretl** [comment]
Implemented in 678a4711cc889e0af5edad258415f51327910f3c, will be part of next release.
