### ISSUE TITLE
Change PDK to SG13G2

### ISSUE THREAD

**Issue by grundOPS** [iic-jku/IIC-OSIC-TOOLS#61]
Following Kwantae Kim's step-by-step introductions, everything is set up fine. However, changing the PDK in .bashrc is only explained for Skywater and GlobalFoundries. How do I set the variables properly for the SG13G2 PDK?

**Comment by hpretl** [comment]
You can use the `iic-pdk` script, so just use `iic-pdk sg13g2` to switch to IHP, and this script also works for the other PDKs (as long as they are installed). Calling `iic-pdk` w/o argument shows which PDKs are available.
