### ISSUE TITLE
Adding jq - a CLI json processor

### ISSUE THREAD

**Issue by phsauter** [iic-jku/IIC-OSIC-TOOLS#63]
We use the jq CLI tool to write configurations of our hardware (along other information) to a file, for example [here](https://github.com/pulp-platform/cheshire-ihp130-o/blob/5cc41c19abf44c8051076ba5709a98c97b7fd156/iguana.mk#L82)

Could you add this tool or do you have another/better way to do something similar?

**Comment by hpretl** [comment]
Added with 07afa246a04244b330b5863020fb00f3a0f7d60f, will be part of next release.

**Comment by hpretl** [comment]
@phsauter I have just pushed an image with tag `next` including this change, please test it if you have time.

**Comment by hpretl** [comment]
Released with `2024.09` tag.
