### ISSUE TITLE
Updating my OSIC Tools

### ISSUE THREAD

**Issue by Camisad0** [iic-jku/IIC-OSIC-TOOLS#67]
Hi.

I have already installed my osictools through docker and able to access the remote server through localhost noVNC. However, I was made aware that there are some updates. How do I specifically update my own docker OSIC Tools to the latest versions including the latest versions of the tools like NGSPICE? Do I need to reinstall this repo in the docker?

Please advise. 

Thanks.

**Comment by hpretl** [comment]
The image can easily be updated to the latest version with `docker pull hpretl/iic-osic-tools:latest`. Then, you need to start a new virtual machine (just answer the prompt correctly when doing `start_vnc.sh`.
