### ISSUE TITLE
Appending to XSCHEM_LIBRARY_PATH

### ISSUE THREAD

**Issue by curtisma** [iic-jku/iic-osic-tools#7]
### **Is your feature request related to a problem? Please describe.**

There's currently no easy way to add to the XSCHEM_LIBRARY_PATH.   The user may want to add part of their repo or workspace to it to let xschem know where to look for schematics and symbols.

The [xschem documentation](https://xschem.sourceforge.io/stefan/xschem_man/tutorial_xschem_libraries.html) suggests 2 methods of adding symbol and schematic libraries].  Both of them require updating the XSCHEM_LIBRARY_PATH.

The container's .bashrc file defines an alias wrapper for the xschem command which passes the xschemrc file as an environment variable.  When the xschemrc is supplied this way, it is the only initialization file read-in according to the 
[install instructions](https://xschem.sourceforge.io/stefan/xschem_man/install_xschem.html).

```bash
alias xschem='xschem -b --rcfile $PDKPATH/libs.tech/xschem/xschemrc'
alias xschemtcl='xschem --rcfile $PDKPATH/libs.tech/xschem/xschemrc'
```

![image](https://user-images.githubusercontent.com/4685385/230558766-ce99f93a-a39f-4639-84e2-ca21182dc74e.png)

### **Describe the solution you'd like**

Each PDK should have the following TCL code appended to its xschemrc to allow the user to specify paths to include on $XSCHEM_USER_LIBRARIES using the $XSCHEM_USER_LIBRARY_PATH environment variable.  If the environment variable is not defined, then $XSCHEM_LIBRARY_PATH remains unchanged.

```TCL
if { [info exists ::env(XSCHEM_USER_LIBRARY_PATH) ] } {
        append XSCHEM_LIBRARY_PATH :$env(XSCHEM_USER_LIBRARY_PATH)
}
```

### **Describe alternatives you've considered**
- The xschem documentation assumes the user can update the xschemrc in their user home which will be loaded as part of the startup sequence.  Finding a way to load other a user xschemrc would make the xschem setup more flexible but also more prone to setup issues.

### **Additional context**

None

**Comment by hpretl** [comment]
This is a good idea, I have submitted a PR to `open_pdks`, I think this is the correct way to include this feature, see https://github.com/RTimothyEdwards/open_pdks/pull/363.
